apiVersion: v1
kind: Service
metadata:
  name: custom-liveness-demo-service
  labels:
    app: custom-liveness-demo
spec:
  type: LoadBalancer
  selector:
    app: custom-liveness-demo
  ports:
  - port: 8080
    targetPort: 8080
